#cloud-config 
users:
  - default
  - name: crawl
    groups: users, adm
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - <<your_ssh_public_key>>
package_update: true
package_upgrade: true
packages:
 - python3-pip
 - git
 - git-lfs
 - build-essential
 - libssl-dev
 - libffi-dev
 - python3-dev
 - libwebp-dev
 - libjpeg-dev
 - python3-venv
write_files:
- path: /etc/environment
  content: |
    CAH_NICKNAME="<<your_nickname>>"
    PYTHONHASHSEED=0
  append: true
runcmd:
 - [ ls, -l, / ]
 - [ sh, -xc, "echo $(date) ': hello crawl!'" ]
 - [ sh, -c, echo "=========hello crawl'=========" ]
 - ls -l /root
 # make swap file so tensorflow and pytorch can install
 #- fallocate -l 5G /swapfile
 #- chmod 600 /swapfile
 #- mkswap /swapfile
 #- swapon /swapfile
 #- cp /etc/fstab /etc/fstab.bak
 #- 'echo "/swapfile none swap sw 0 0" | tee -a /etc/fstab'
 #- sysctl vm.swappiness=75
 #- 'echo "vm.swappiness=75" | tee -a /etc/sysctl.conf'
 # make ramdisk (actually no need for ramdisk)
 # - 'echo "tmpfs  /home/crawl/save  tmpfs  rw,size=512M  0   0" | tee -a /etc/fstab'
# take care of max open files
 - echo "* soft     nproc          65535 " >> /etc/security/limits.conf
 - echo "* hard     nproc          65535 " >> /etc/security/limits.conf
 - echo "* soft     nofile         65535" >> /etc/security/limits.conf
 - echo "* hard     nofile         65535" >> /etc/security/limits.conf
 - echo "root soft     nproc          65535 " >> /etc/security/limits.conf
 - echo "root hard     nproc          65535 " >> /etc/security/limits.conf
 - echo "root soft     nofile         65535" >> /etc/security/limits.conf
 - echo "root hard     nofile         65535" >> /etc/security/limits.conf
 - echo "session required pam_limits.so" >> /etc/pam.d/common-session
 - echo "fs.file-max = 2097152" >> /etc/sysctl.conf
# install git lfs
 - git lfs install
 - git lfs track "duplicates*.txt"
# secure ssh
 - sed -i -e '/^\(#\|\)PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
 - sed -i -e '/^\(#\|\)PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
 - sed -i -e '/^\(#\|\)X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
 - sed -i -e '/^\(#\|\)MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
 - sed -i -e '/^\(#\|\)AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
 - sed -i -e '/^\(#\|\)AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
 - sed -i -e '/^\(#\|\)AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh\/authorized_keys/' /etc/ssh/sshd_config
 - sed -i '$a AllowUsers crawl' /etc/ssh/sshd_config
 # install the script
 - cd /home/crawl
 - git clone https://github.com/rvencu/crawlingathome-gpu-hcloud
 - cd crawlingathome-gpu-hcloud
 - bash worker-setup.sh
 # make the script run as a service at startup
 - echo "[Unit]" >> /etc/systemd/system/crawl.service
 - echo "After=network.service" >> /etc/systemd/system/crawl.service
 - echo "Description=Crawling @ Home" >> /etc/systemd/system/crawl.service
 - echo "[Service]" >> /etc/systemd/system/crawl.service
 - echo "Type=simple" >> /etc/systemd/system/crawl.service
 - echo "LimitNOFILE=2097152" >> /etc/systemd/system/crawl.service
 - echo "WorkingDirectory=/home/crawl" >> /etc/systemd/system/crawl.service
 - echo "ExecStart=/home/crawl/crawl.sh" >> /etc/systemd/system/crawl.service
 - echo "EnvironmentFile=/etc/environment" >> /etc/systemd/system/crawl.service
 - echo "User=crawl" >> /etc/systemd/system/crawl.service
 - echo "[Install]" >> /etc/systemd/system/crawl.service
 - echo "WantedBy=multi-user.target" >> /etc/systemd/system/crawl.service
 - chmod 664 /etc/systemd/system/crawl.service
 - systemctl daemon-reload
 - systemctl enable crawl.service
 - echo "#!/bin/bash" >> /home/crawl/crawl.sh
 - echo "while true" >> /home/crawl/crawl.sh
 - echo "do" >> /home/crawl/crawl.sh
 - echo "python3 -u /home/crawl/crawlingathome-gpu-hcloud/worker.py >> /home/crawl/crawl.log 2>&1" >> /home/crawl/crawl.sh
 - echo "sleep 1" >> /home/crawl/crawl.sh
 - echo "done" >> /home/crawl/crawl.sh
 - chmod 744 /home/crawl/crawl.sh
 - chown crawl:adm -R /home/crawl/
 - apt clean
 - reboot
final_message: "The system is finally up, after $UPTIME seconds"
